# Generated by Django 3.1.4 on 2020-12-29 20:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRoom',
            fields=[
                ('id', models.CharField(default=core.models.string_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.CharField(max_length=20, unique=True)),
                ('booking_email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('sitting_count', models.IntegerField()),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('AVAILABLE', 'Available')], default='AVAILABLE', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
